apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: router
spec:
  replicas: 1
  selector:
    matchLabels:
      app: router
  template:
    metadata:
      labels:
        app: router
      annotations:
        prometheus.io/scrape: "true"
    spec:
        containers:
        - name: router
          image: router
          imagePullPolicy: Never
          env:
          - name: UPDATED_AT
            value: "Fri May 25 20:45:49 PDT 2018"
          - name:  MICRO_REGISTRY
            value:  kubernetes
          - name: MINIO_EXTERNAL_URL
            value: "http://192.168.1.74:30366"
          - name: JAEGER_SERVICE_NAME
            value: router-svc
          - name: JAEGER_AGENT_HOST
            value: jaeger-agent
          - name: JAEGER_SAMPLER_TYPE
            value: const
          - name: JAEGER_SAMPLER_PARAM
            value: "1"
          - name: JAEGER_REPORTER_LOG_SPANS
            value: "true"
          - name: OPENTRACING_METRICS_EXPORTER_HTTP_PATH
            value: "/metrics"
          ports:
          - name: router-port
            containerPort: 8080
          - name: prometheus
            containerPort: 9090