apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: router
spec:
  replicas: 1
  selector:
    matchLabels:
      app: router
  template:
    metadata:
      labels:
        app: router
    spec:
        containers:
        - name: router
          image: router
          imagePullPolicy: Never
          env:
          - name: UPDATED_AT
            value: "Wed May 16 20:04:01 PDT 2018"
          - name:  MICRO_REGISTRY
            value:  kubernetes
          - name: MINIO_EXTERNAL_URL
            value: "http://192.168.99.100:31724"
          ports:
          - containerPort: 8080
            name: router-port