apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: router
spec:
  replicas: 1
  selector:
    matchLabels:
      app: router
  template:
    metadata:
      labels:
        app: router
    spec:
        containers:
        - name: router
          image: router
          imagePullPolicy: Never
          env:
          - name: UPDATED_AT
            value: "Mon May 14 19:08:20 PDT 2018"
          - name:  MICRO_REGISTRY
            value:  kubernetes
          ports:
          - containerPort: 8080
            name: router-port