apiVersion: v1
kind: Service
metadata:
  name: router
  labels:
    app: router
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: router
status:
  loadBalancer: {}